name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
    - run: gyro add mattnite/version
